version: '3.8'
services:
  db:
    image: mariadb:latest
    volumes:
      - d2mariadbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DBUSER=root
      - DBPASSWORD=my-secret-pw
    depends_on:
      - db
  mailhog:
    ports:
      - "587:587"
      - "8025:8025"
    image: 42bv/mailhog:latest
volumes:
  d2mariadbdata: ~